### ISSUE TITLE
Move Default Text Editor plugin under EclipseLabs

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipselabs/eclipselabs#1]
I have a small plug-in that I want to have under EclipseLabs. It is currently in this repo: https://github.com/kaloyan-raev/default-text-editor

Let me know what steps are necessary to make the move.

**Comment by waynebeaton** [comment]
Hi Kaloyan. Please transfer ownership of the repository to waynebeaton. I will move the project to Eclipse Labs and create a team for the repository with you as administrator.

**Comment by kaloyan-raev** [comment]
Hi @waynebeaton. Transfer requested.

**Comment by waynebeaton** [comment]
I've moved the repository and have created an administration team with you as a member. If I understand correctly, you should have admin rights on the repo. 

Can you confirm that your admin rights do not extend beyond the repo?

**Comment by kaloyan-raev** [comment]
I can create new repositories in the eclipselabs organization. Perhaps, this is not an expected effect.

**Comment by kaloyan-raev** [comment]
I can also make my (and only mine) membership in the organization publicly visible. This should not be a problem.

**Comment by waynebeaton** [comment]
Rats. I created a team with "admin" rights based on the description: "This team will be able to push/pull to its repositories, as well as add other collaborators to them." I understood "its" to mean "the team's".

Can you mess with any of the other repositories that are already there?

**Comment by kaloyan-raev** [comment]
It seems I have no write access to any of the rest of the existing repos - I don't see their Settings link, I cannot edit description, etc.

**Comment by kaloyan-raev** [comment]
Here is some documentation on permission levels: https://help.github.com/articles/permission-levels-for-an-organization-repository/

**Comment by waynebeaton** [comment]
It looks like this is behaving as expected.

https://help.github.com/articles/permission-levels-for-an-organization-repository/

Since anybody can create a new repository on the existing Eclipse Labs, I don't think that it's a problem for a team administrator to create additional repositories.

I think that we're done. Though, I will bring this up on the Bugzilla record we're using to track this.
