### ISSUE TITLE
smart-datasource-object-factory

### ISSUE THREAD

**Issue by delchev** [eclipselabs/eclipselabs#10]
smart-datasource-object-factory is a Datasource Object Factory, which creates a datasource from resource definition and environment variables. It delegates the actual instance creation to the default object factory. Afterwards it gets injected into the JNDI of the Web Container (e.g. Tomcat 8).

**Comment by waynebeaton** [comment]
Dirigible work has moved to DirigibleLabs. I assume that this is no longer an issue.
