### ISSUE TITLE
Move Yakindu Statechart Tools to Eclipselabs Github

### ISSUE THREAD

**Issue by andreasmuelder** [eclipselabs/eclipselabs#2]
elcipselabs google code closes the doors so we have to move to github with Yakindu Statechart Tools in some way. 

Project Website: (http://www.statecharts.org)
Source code: https://code.google.com/a/eclipselabs.org/p/yakindu/

We need assistance in a couple of things:
- The source code is still in an SVN repository. We want to move to GIT but keeping the history, tags and branches.
- We also want to migrate the issue tracker
- We want to create an eclipse proposal in the not-so-far future

Any help is appreciated!

Regards,

Andreas

**Comment by waynebeaton** [comment]
Hi Andreas. Before we can move the project into EclipseLabs, you'll have to move it into a personal repository on GitHub. There are tools that you can use to migrate the existing SVN repository with history to Git. e.g. http://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git

I don't know how to migrate issues. I did a quick Google search and there does appear to be some options, including some online tools that may do the job. Note that when you do move the project to Eclipse, our current rules require that project issues be tracked in our Bugzilla instance.

**Comment by andreasmuelder** [comment]
Hi Wayne, we decided to create a Yakindu organisation and added statechart tools to it:
https://github.com/Yakindu/statecharts
Thanks for your help, this issue can be closed.
BTW: The google code exporter is really nice - all issues are migrated to github automatically.
