### ISSUE TITLE
Move Passerelle to the new eclipselabs

### ISSUE THREAD

**Issue by erwindl0** [eclipselabs/eclipselabs#4]
Dear administrators,

I would like to move our Passerelle project from the eclipselabs@Google to this new one.

I'll push the magical export-to-github button tomorrow and then transfer ownership to you.
Can you let me know which administrator account to transfer it to?

thanks,
erwin

**Comment by waynebeaton** [comment]
I'll take care of it. Assign it to waynebeaton

**Comment by erwindl0** [comment]
Thanks for the support.
Unfortunately the export failed without detailed error info. But from the FAQ it seems the reason could be that our SVN repos is a little bit too big (> 1GB).

So I'll go for a manual process to just replicate the trunk for the main modules. I'll see later on if/how to add some important previous tags/branches.

**Comment by jayjaybillings** [comment]
I'm going to keep an eye on this because I need to learn how to handle the transfer. Erwin and I talked about it on our phone call yesterday, but I'm just not as fast as Wayne. ;-)

**Comment by erwindl0** [comment]
The passerelle repos is ready on https://github.com/erwindl0/passerelle
When I try to transfer ownership to the organization "eclipselabs", I get an error saying that I need to be an administrator of eclipselabs.

Is this expected? If so, can you make me an eclipselabs administrator?

regards
erwin

**Comment by jayjaybillings** [comment]
This is expected. You need to transfer ownership to Wayne or me. Go with
Wayne for now so I can just observe the process since I have never done it
before.

**Comment by erwindl0** [comment]
Ok, seems logical but I guess the workflow described in bugzilla   could 
be slightly adapted then :
- Project member migrates their repository to GitHub
- Assign ownership to_an administrator of_  the eclipselabs organization
- EclipseLabs administrator takes ownership
- EclipseLabs administrator sets up a team for each repository
  with the the de facto project lead as administrator; maintaining the team is their problem.

going for the next step ;-)

Jay Jay Billings schreef op 04/06/2015 om 13:03:

> This is expected. You need to transfer ownership to Wayne or me. Go with
> Wayne for now so I can just observe the process since I have never done it
> before.

**Comment by waynebeaton** [comment]
I accepted the transfer to my personal account and then transferred it to eclipselabs.

I've set up an admin team and have added Erwin as a member and assigned the repository to that team. You should be good-to-go.

Jay, I'm not sure if watching this was helpful. I'm not quite sure how to make it so. Maybe next time, you should just go for it...

I think that we're done here. Once you confirm that you're functional, Erwin, please close this issue.

**Comment by jayjaybillings** [comment]
Wayne, I'll just go for it next time, but it was actually helpful this
time. :)

On Thu, Jun 4, 2015 at 4:06 PM, Wayne Beaton notifications@github.com
wrote:

> I accepted the transfer to my personal account and then transferred it to
> eclipselabs.
> 
> I've set up an admin team and have added Erwin as a member and assigned
> the repository to that team. You should be good-to-go.
> 
> Jay, I'm not sure if watching this was helpful. I'm not quite sure how to
> make it so. Maybe next time, you should just go for it...
> 
> I think that we're done here. Once you confirm that you're functional,
> Erwin, please close this issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eclipselabs/eclipselabs/issues/4#issuecomment-109033473
> .

## 

Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings

**Comment by erwindl0** [comment]
It works fine! I just tried a clone & some dummy commit&push.

thanks
erwin
