### ISSUE TITLE
Add extra passerelle teams

### ISSUE THREAD

**Issue by erwindl0** [eclipselabs/eclipselabs#5]
We would need to be able to differentiate permissions of Passerelle members.

Could you create an extra team for this : passerelle-write ? (or is there another naming convention?)

thanks
erwin

**Comment by jayjaybillings** [comment]
Done!

Jay

**Comment by erwindl0** [comment]
Thanks Jay.

One remaining problem : it seems I can not add members in that one.

In the passerelle-admin that feature is present/allowed, but not in the passerelle-write team.
Can that be switched on?

erwin.

**Comment by jayjaybillings** [comment]
Erwin,

I just looked and I couldn't find how to do that. I am going to assign this to Wayne to see if he knows how to fix it.

Jay

**Comment by waynebeaton** [comment]
AFAICT you need to be an organization admin to add users to the "write" group.

It looks like we have two choices: 

I'm pretty sure that members of the admin group can add additional members to the admin group; or
Organization administrators will have to add members to the write group.

Both options are, IMHO, suboptimal.

Thoughts?

**Comment by jayjaybillings** [comment]
I agree that both are suboptimal. I question why there needs to be two
Passerelle teams and why one isn't enough. Essentially passerelle-admin is
the same as the passerelle-write group with the organization as the
administrators of that.

Erwin, thoughts?

Jay

On Fri, Jun 5, 2015 at 2:14 PM, Wayne Beaton notifications@github.com
wrote:

> AFAICT you need to be an organization admin to add users to the "write"
> group.
> 
> It looks like we have two choices:
> 
> I'm pretty sure that members of the admin group can add additional members
> to the admin group; or
> Organization administrators will have to add members to the write group.
> 
> Both options are, IMHO, suboptimal.
> 
> Thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eclipselabs/eclipselabs/issues/5#issuecomment-109384342
> .

## 

Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings

**Comment by erwindl0** [comment]
Hi Jay, Wayne,

Thanks for your feedback.

I was looking for a way to differentiate core members from contributors.
But indeed, if this is not supported in a simple way, I think we'll 
forget about the 2 teams.

Can you delete the passerelle-write team again?
(I've left it)

Sorry for the trouble...

regards
erwin

Jay Jay Billings schreef op 05/06/2015 om 20:23:

**Comment by jayjaybillings** [comment]
Thanks Erwin and no worries. I just deleted the team.

Jay
