### ISSUE TITLE
Groovy Dev Platform powered by Eclipse Dirigible

### ISSUE THREAD

**Issue by delchev** [eclipselabs/eclipselabs#6]
Hi Webmaster,

We would like to have a separate repository under EclipseLabs to provide the Groovy language support plugins in Eclipse Dirigible context. This project will have pre-configured and tailored features for Groovy developers as well as the corresponding packaging project.

Regards,
Nedelcho

**Comment by kaloyan-raev** [comment]
Do you want a new empty repository under EclipseLabs or do you want to transfer an existing GitHub repository under EclipseLabs?

**Comment by delchev** [comment]
Hi Kaloyan,

Best option is to have a clone of eclipse/dirigible project with a new name under eclipselabs (not transfer, but clone ;) )

Regards,
Nedelcho

**Comment by kaloyan-raev** [comment]
I forked eclipse/dirigible to eclipselabs/dirigible-groovy. Let me know if this is what you meant by saying "clone". Alternatively, I can create an empty eclipselabs/dirigible-groovy and you can push whatever you want as an initial commit.

You should have an invitation for being an admin of this repository.

If everything is OK for you I will proceed with your other requests in the same way.

**Comment by delchev** [comment]
Yes, it is perfect!
The same should apply for the dirigible-ruby project
