### ISSUE TITLE
Ruby Dev Platform powered by Eclipse Dirigible

### ISSUE THREAD

**Issue by delchev** [eclipselabs/eclipselabs#7]
Hi Webmaster,

We would like to have a separate repository under EclipseLabs to provide the Ruby language support plugins in Eclipse Dirigible context. This project will have pre-configured and tailored features for Ruby developers as well as the corresponding packaging project.

Regards,
Nedelcho

**Comment by kaloyan-raev** [comment]
@delchev It's not possible to fork the same repository more than once in the same organization account. Therefore, I created a new empty dirigible-ruby repository. You need to push the cloned content yourself.
