### ISSUE TITLE
MongoDB JDBC Driver

### ISSUE THREAD

**Issue by delchev** [eclipselabs/eclipselabs#8]
Hi Webmaster,

We would like to have a separate repository under EclipseLabs to provide a standalone JDBC Driver for MongoDB. It will play a role, in Eclipse Dirigible context, of a communication channel for MongoDB as well as example for adapting NoSQL databases APIs to JDBC.

Regards,
Nedelcho

**Comment by kaloyan-raev** [comment]
@delchev I guess you need a new empty repository under the eclipselabs account, right? Let me know the preferred name for the repository, e.g. mongodb-jdbc-driver.

**Comment by delchev** [comment]
yes, this one is perfect "mongodb-jdbc-driver"

**Comment by kaloyan-raev** [comment]
I created the repository: https://github.com/eclipselabs/mongodb-jdbc-driver

Please, check it and close the issue if everything works OK for you.

**Comment by delchev** [comment]
Thanks!
