### ISSUE TITLE
Java Dev Platform powered by Eclipse Dirigible

### ISSUE THREAD

**Issue by delchev** [eclipselabs/eclipselabs#9]
Hi Webmaster,

We would like to have a separate repository under EclipseLabs to provide the Java language support plugins in Eclipse Dirigible context. This project will have pre-configured and tailored features for Java developers as well as the corresponding packaging project.

The same is currently available in the master branch of eclipse/dirigible, but will be removed in the next release as soon as we will stick to JavaScript only default language with full vertical support.

Regards,
Nedelcho

**Comment by kaloyan-raev** [comment]
Nedelcho, do you need a fork of the eclipse/dirigible repository under the eclipselabs account, or do you need a new empty repository. If it is the latter, please suggest a name.

**Comment by delchev** [comment]
Just an empty repository with name "dirigible-java" will be perfect. Thanks!

**Comment by kaloyan-raev** [comment]
Done: https://github.com/eclipselabs/dirigible-java
